
### DISASTER RECOVERY SETTINGS

# DR ile ilgili ayarlar
# Eğer true ise DR kurulumu devreye girecek. DR kurulumu için hosts.ini içerisindeki DR vault_dr hostları dikkate alınılacaktır.
# Disaster yapısının çalışması için Prod vault sunucuları bu ansible playbook ile yapılandırılması gerekmektedir. 5 Dakikada bir prod cluster'ı DR Cluster'ı ile eşitlemektedir.
dr_enabled: false 

# keepalived servisi için virtual ip adresini belirtiniz.
vault_dr_virtual_ip_address: "192.168.118.200"

# /etc/hosts dosyası için domain ve sunucu isimlerine göre düzenleme yapınız. Domain isimlerini tanımlarken sertifika ile uyumluluğunu kontrol ediniz.
hosts_entries:
  - ip: "192.168.118.133"
    fqdn: "dr-vault01.domain.com"
    short: "dr-vault01"
  - ip: "192.168.118.134"
    fqdn: "dr-vault02.domain.com"
    short: "dr-vault02"
  - ip: "192.168.118.135"
    fqdn: "dr-vault03.domain.com"
    short: "dr-vault03"
  - ip: "192.168.118.200" # virtual ip address
    fqdn: "dr-vault.domain.com"  # vault domain adresi, uygulama erişimleri ve arayüz için kullanılacaktır.
    short: "dr-vault"

# DEBIAN/UBUNTU
# iptables kurulumu ile devam etmek için iptables_install parametresini true yapınız. mevcut firewall'unuz varsa false yapınız.
# iptables kurallarını sunucu ip adreslerine göre düzenlemeliyiz. Virtual ip adresini dahil etmelisiniz.
iptables_install: true
iptables_rules_v4:
  - "-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT"
  - "-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT"
  - "-A INPUT -p tcp -m tcp --dport 8200 -j ACCEPT"
  - "-A INPUT -s 192.168.118.133/32 -p tcp -m tcp -j ACCEPT"
  - "-A INPUT -s 192.168.118.134/32 -p tcp -m tcp -j ACCEPT"
  - "-A INPUT -s 192.168.118.135/32 -p tcp -m tcp -j ACCEPT"
  - "-A INPUT -s 192.168.118.133/32 -p udp -m udp -j ACCEPT"
  - "-A INPUT -s 192.168.118.134/32 -p udp -m udp -j ACCEPT"
  - "-A INPUT -s 192.168.118.135/32 -p udp -m udp -j ACCEPT"
  - "-A INPUT -s 192.168.117.133/32 -p tcp -m tcp -j ACCEPT" # Prod site
  - "-A INPUT -s 192.168.117.134/32 -p tcp -m tcp -j ACCEPT" # Prod site
  - "-A INPUT -s 192.168.117.135/32 -p tcp -m tcp -j ACCEPT" # Prod site
  - "-A INPUT -s 192.168.117.133/32 -p udp -m udp -j ACCEPT" # Prod site
  - "-A INPUT -s 192.168.117.134/32 -p udp -m udp -j ACCEPT" # Prod site 
  - "-A INPUT -s 192.168.117.135/32 -p udp -m udp -j ACCEPT" # Prod site

## RHEL/OEL
# Rhell/Oel için firewalld kurulumu için yapılandırılması gerekiyorsa "true" yapınız.
firewalld_install: false

# Firewalld tarafında açılacak kurallar (örnek)
# Basitçe port açma veya servis açma şeklinde tanımlayabilirsiniz
firewalld_rules:
  - service: ssh
  - port: "443/tcp"
  - port: "8200/tcp"
  - port: "8201/tcp"
  - port: "122/tcp"
  - port: "22/tcp"


# Kaynak IP engelleme/izin gibi gelişmiş senaryolar için

 #  - source: "192.168.117.133/32"
 #    port: "8200/tcp"
 #  - source: "192.168.117.134/32"
 #    port: "8200/tcp"
 #  - source: "192.168.117.135/32"
 #    port: "8200/tcp"
 #  - source: "192.168.117.133/32"
 #    port: "443/tcp"
 #  - source: "192.168.117.134/32"
 #    port: "443/tcp"
 #  - source: "192.168.117.135/32"
 #    port: "443/tcp"
