# This domain name will be used in application access and config files.
# Ensure that it is compatible with the certificate being used.
vault_domain_name: "domain.com"

# Specify the virtual IP address for the keepalived service.
vault_virtual_ip_address: "192.168.117.200"

# Update the /etc/hosts file based on domain and server names.
# Ensure domain names are compatible with the certificate. To activate /etc/hosts settings, do "hosts_entries_enabled: true"
hosts_entries_enabled: false
hosts_entries:
  - ip: "192.168.117.133"
    fqdn: "vault01.domain.com"
    short: "vault01"
  - ip: "192.168.117.134"
    fqdn: "vault02.domain.com"
    short: "vault02"
  - ip: "192.168.117.135"
    fqdn: "vault03.domain.com"
    short: "vault03"
  - ip: "192.168.117.200" # virtual IP address
    fqdn: "vault.domain.com"  # This address will be used for application access and UI.
    short: "vault"

# DEBIAN/UBUNTU
# Set iptables_install to true to proceed with iptables installation.
# If you already have a firewall, set it to false.
# iptables rules must be configured based on server IP addresses.
# Be sure to include the virtual IP address as well.
iptables_install: true
iptables_rules_v4:
  - "-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT"
  - "-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT"
  - "-A INPUT -p tcp -m tcp --dport 8200 -j ACCEPT"
  - "-A INPUT -s 192.168.117.133/32 -p tcp -m tcp -j ACCEPT"
  - "-A INPUT -s 192.168.117.134/32 -p tcp -m tcp -j ACCEPT"
  - "-A INPUT -s 192.168.117.135/32 -p tcp -m tcp -j ACCEPT"
  - "-A INPUT -s 192.168.117.133/32 -p udp -m udp -j ACCEPT"
  - "-A INPUT -s 192.168.117.134/32 -p udp -m udp -j ACCEPT"
  - "-A INPUT -s 192.168.117.135/32 -p udp -m udp -j ACCEPT"

## RHEL/OEL
# Set to true if firewalld installation/configuration is required for RHEL/OEL.
firewalld_install: false

# Rules to be opened on firewalld (example)
# You can define ports or services simply.
firewalld_rules:
  - service: ssh
  - port: "443/tcp"
  - port: "8200/tcp"
  - port: "8201/tcp"
  - port: "122/tcp"
  - port: "22/tcp"

# For advanced scenarios such as source IP blocking/allowing

 #  - source: "192.168.117.133/32"
 #    port: "8200/tcp"
 #  - source: "192.168.117.134/32"
 #    port: "8200/tcp"
 #  - source: "192.168.117.135/32"
 #    port: "8200/tcp"
 #  - source: "192.168.117.133/32"
 #    port: "443/tcp"
 #  - source: "192.168.117.134/32"
 #    port: "443/tcp"
 #  - source: "192.168.117.135/32"
 #    port: "443/tcp"

# Sysctl parameters to be applied on Vault servers.
# Revise these settings based on your server resources.
vault_sysctl_vars:
  "vm.swappiness": 0
  "vm.vfs_cache_pressure": 75
  "vm.dirty_background_ratio": 5
  "vm.dirty_ratio": 60
  "vm.max_map_count": 262144
  "fs.file-max": 262144
  "fs.suid_dumpable": 0
  # Additional networking parameters (commented out)
  #"net.core.wmem_default": 25165824
  #"net.core.rmem_default": 25165824
  #"net.core.wmem_max": 25165824
  #"net.core.rmem_max": 25165824
  #"net.ipv4.tcp_wmem": "20480 12582912 25165824"
  #"net.ipv4.tcp_rmem": "20480 12582912 25165824"
  #"net.ipv4.tcp_mem": "65536 25165824 262144"
  #"net.ipv4.udp_mem": "65536 25165824 262144"
  #"net.ipv4.udp_wmem_min": 16384
  #"net.ipv4.udp_rmem_min": 16384
  #"net.ipv4.tcp_window_scaling": 1
  #"net.ipv4.tcp_max_syn_backlog": 10240
  #"net.core.netdev_max_backlog": 65536
  #"net.core.optmem_max": 25165824
  #"net.ipv4.tcp_synack_retries": 2
  #"net.ipv4.ip_local_port_range": "2048 65535"
  #"net.ipv4.tcp_rfc1337": 1
  #"net.ipv4.tcp_fin_timeout": 15
  #"net.core.somaxconn": 4096
  #"net.ipv4.tcp_syncookies": 1
  #"net.ipv4.icmp_echo_ignore_broadcasts": 1
  #"net.ipv4.icmp_ignore_bogus_error_responses": 1

# Chrony NTP servers
# To activate chrony settings, do "ntp_servers_enabled: true"
ntp_servers_enabled: false
ntp_servers:
  - "0.tr.pool.ntp.org"
  - "1.tr.pool.ntp.org"

# Specify the Vault version.
# For a different version tag, refer to: https://releases.hashicorp.com/vault/

## For debian/ubuntu: use 'vault_deb_version: "vault=1.18.5-1"'
## For rhel/oel: use 'vault_rhel_version: "vault-1.18.5-1"'

vault_deb_version: "vault=1.18.5-1" # debian/ubuntu
vault_rhel_version: "vault-1.18.5-1" # rhel/oel
vault_init_keys: 5
vault_init_threshold: 2
vault_cluster_name: "SAMPLE-CLUSTER"
vault_log_level: "info" # Options: trace, info, debug, error, warning

# Self-signed (true) or wildcard (false)
# Self-signed support is in development.
# If set to false, you can place your own certificates under roles/vault/files.
# A sample certificate is provided for file naming reference.
self_signed: false
self_signed_cert_days: "730"

# SAN information required for self-signed certificates
vault_tls_alt_names:
  dns:
    - "*.domain.com"
    - "vaul01.domain.com"
    - "vaul02.domain.com"
    - "vaul03.domain.com"
    - "vault.domain.com"
  ip:
    - "127.0.0.1"
    - "192.168.117.133"
    - "192.168.117.134"
    - "192.168.117.135"
    - "192.168.117.200"

# You can adjust the Vault TLS and raft paths according to your system.
# vault_key_path is used to deliver unseal keys to the specified location on the first Vault server.
vault_tls_path: "/opt/vault-tls"
vault_raft_path: "/opt/datavault/raft"
vault_key_path: "/etc/vault.d/vault_init.json"
vault_audit_path: "/var/log/vault" # Specify the audit log directory. Only the leader server will store audit logs. Adjust your SIEM product considering possible leader changes.
auditlog_retention_days: 7 # Logrotate retention period for audit logs
auditlog_logrotate_path: "/etc/logrotate.d/vault_audit" # Path to the logrotate config file for audit logs

# To activate the backup structure, define the following variables:
backup_enabled: true # If false, the backup structure will not be created.
backup_retention_days: 30  # Number of backups to retain
backup_path: /backup/vault-backup  # Directory where backups will be stored
backup_webhook_url: "https://example.webhook.office.com/webhookb2/..."  # Webhook URL for backup notifications
backup_cron_schedule: "0 2 * * *"  # Runs every day at 2:00 AM. Backups will be managed by the crontab on the leader node.
backup_platform: "teams" # Choose between: slack, teams, discord, generic
backup_domain_address: "https://vault.domain.com:8200" # Adjust this address based on the domain name assigned to the virtual IP. If this address is not resolvable, backup will not run.

# After wiping all configurations, set this to true to allow reboot.
# This parameter only works with the "uninstall.yml" playbook.
reboot_after_uninstall: false
