{
 "title": "Hashicorp Vault",
 "description": " Hashicorp Vault Metrics",
 "tags": [ "vault" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job:",
    "query": "label_values(up{job=~\"vault.*\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster:",
    "query": "label_values(up{job=\"$job\"}, cluster)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(up{job=\"$job\", cluster=\"$cluster\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(up{job=\"$job\", cluster=\"$cluster\", instance=~\"$node:(.*)\"}, instance)"
   },
   {
    "name": "mountpoint",
    "label": "Mount Point:",
    "query": "label_values(vault_secret_kv_count{job=\"$job\", cluster=\"$cluster\"}, mount_point)"
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\", cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_secret_kv_count{job=\"$job\", cluster=\"$cluster\"})",
     "legendFormat": "{{ mount_point }}"
    }
   ]
  },
  {
   "title": "Number of Identity Entities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_identity_num_entities{job=\"$job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Identity Entities Aliases by Method",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg without(instance) (vault_identity_entity_alias_count{job=\"$job\", cluster=\"$cluster\"})",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(1 + vault_core_unsealed{job=\"$job\", cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of Leases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_expire_num_leases{job=\"$job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "mountpoint",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Operations in 5 minute" }
     ],
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count{job=\"$job\", cluster=\"$cluster\"}[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count{job=\"$job\", cluster=\"$cluster\"}[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count{job=\"$job\", cluster=\"$cluster\"}[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count{job=\"$job\", cluster=\"$cluster\"}[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "µs", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum{job=\"$job\", cluster=\"$cluster\"}[1m]) / rate(vault_route_create_${mountpoint}__count{job=\"$job\", cluster=\"$cluster\"}[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum{job=\"$job\", cluster=\"$cluster\"}[1m]) / rate(vault_route_delete_${mountpoint}__count{job=\"$job\", cluster=\"$cluster\"}[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum{job=\"$job\", cluster=\"$cluster\"}[1m]) / rate(vault_route_read_${mountpoint}__count{job=\"$job\", cluster=\"$cluster\"}[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum{job=\"$job\", cluster=\"$cluster\"}[1m]) / rate(vault_route_list_${mountpoint}__count{job=\"$job\", cluster=\"$cluster\"}[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  { "title": "CPU/Mem Info: $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Heap Objects Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_heap_objects{job=\"$job\", cluster=\"$cluster\"} / vault_runtime_malloc_count{job=\"$job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_num_goroutines{job=\"$job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Allocated MB",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(vault_runtime_alloc_bytes{job=\"$job\", cluster=\"$cluster\"})",
     "legendFormat": "$node"
    }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Available Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_token_count{job=\"$job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Tokens by Policy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_policy{job=\"$job\", cluster=\"$cluster\"})",
     "legendFormat": "{{ policy }}"
    }
   ]
  },
  {
   "title": "Pending Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_token_create_count{job=\"$job\", cluster=\"$cluster\"} - vault_token_store_count{job=\"$job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Tokens by TTL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_ttl{job=\"$job\", cluster=\"$cluster\"})",
     "legendFormat": "{{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Tokens by Auth Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_auth{job=\"$job\", cluster=\"$cluster\"})",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Tokens Creation by Method & TTL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(auth_method, creation_ttl) (vault_token_creation{job=\"$job\", cluster=\"$cluster\"})",
     "legendFormat": "{{ auth_method }} - {{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Token Creation/Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_create_count{job=\"$job\", cluster=\"$cluster\"})",
     "legendFormat": "Create"
    },
    {
     "expr": "avg without(instance) (vault_token_store_count{job=\"$job\", cluster=\"$cluster\"})",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Token Lookups",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Lookups per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_token_lookup_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Lookups"
    }
   ]
  },
  { "title": "Audit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Log Request Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_request_failure{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Log Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_audit_log_request_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Request "
    },
    {
     "expr": "avg(irate(vault_audit_log_response_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Response"
    },
    {
     "expr": "avg(irate(vault_core_handle_request_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Consul Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_consul_get_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "GET"
    },
    {
     "expr": "avg(irate(vault_consul_put_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "avg(irate(vault_consul_delete_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "irate(vault_consul_list_count{job=\"$job\", cluster=\"$cluster\", instance=\"$node:$port\"}[1m])",
     "legendFormat": "LIST"
    }
   ]
  },
  {
   "title": "Log Response Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_response_failure{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  { "title": "Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Policy Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_policy_set_policy_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "SET"
    },
    {
     "expr": "avg(irate(vault_policy_delete_policy_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "avg(irate(vault_policy_list_policies_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "LIST"
    }
   ]
  },
  {
   "title": "Policy Get",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_policy_get_policy_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "GET"
    }
   ]
  },
  { "title": "Raft Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Raft Leader Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vault_core_active{job=\"$job\", cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cluster Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(vault_core_active{job=\"$job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Raft Applied Index",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(vault_raft_storage_stats_applied_index{job=\"$job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Raft Index Lag",
   "type": "stat",
   "description": "Difference between max and min applied index across nodes. High values indicate replication lag.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(vault_raft_storage_stats_applied_index{job=\"$job\", cluster=\"$cluster\"}) - min(vault_raft_storage_stats_applied_index{job=\"$job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Raft Commit Index",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(vault_raft_storage_stats_commit_index{job=\"$job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Raft Commit Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(vault_raft_commitTime_sum{job=\"$job\", cluster=\"$cluster\"}[5m]) / rate(vault_raft_commitTime_count{job=\"$job\", cluster=\"$cluster\"}[5m]) * 1000)",
     "legendFormat": "Commit Time"
    }
   ]
  },
  {
   "title": "Raft Apply Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "ops", "label": "Operations per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_raft_apply{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Raft Apply"
    }
   ]
  },
  {
   "title": "Raft Applied Index by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vault_raft_storage_stats_applied_index{job=\"$job\", cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Raft Replication Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(vault_raft_replication_appendEntries_rpc_sum{job=\"$job\", cluster=\"$cluster\"}[5m]) / rate(vault_raft_replication_appendEntries_rpc_count{job=\"$job\", cluster=\"$cluster\"}[5m]) * 1000)",
     "legendFormat": "AppendEntries RPC"
    }
   ]
  },
  { "title": "Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Request Latency (Handle Request)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(vault_core_handle_request_sum{job=\"$job\", cluster=\"$cluster\"}[5m]) / rate(vault_core_handle_request_count{job=\"$job\", cluster=\"$cluster\"}[5m]) * 1000)",
     "legendFormat": "Avg Request Time (ms)"
    },
    {
     "expr": "max(rate(vault_core_handle_request_sum{job=\"$job\", cluster=\"$cluster\"}[5m]) / rate(vault_core_handle_request_count{job=\"$job\", cluster=\"$cluster\"}[5m]) * 1000)",
     "legendFormat": "Max Request Time (ms)"
    }
   ]
  },
  {
   "title": "Login Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(vault_core_handle_login_request_sum{job=\"$job\", cluster=\"$cluster\"}[5m]) / rate(vault_core_handle_login_request_count{job=\"$job\", cluster=\"$cluster\"}[5m]) * 1000)",
     "legendFormat": "Avg Login Time (ms)"
    },
    {
     "expr": "max(rate(vault_core_handle_login_request_sum{job=\"$job\", cluster=\"$cluster\"}[5m]) / rate(vault_core_handle_login_request_count{job=\"$job\", cluster=\"$cluster\"}[5m]) * 1000)",
     "legendFormat": "Max Login Time (ms)"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "reqps", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_core_handle_request_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "avg(irate(vault_core_handle_login_request_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Login Requests"
    }
   ]
  },
  { "title": "HA Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "HA Active Node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vault_core_active{job=\"$job\", cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Active Nodes Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(vault_core_active{job=\"$job\", cluster=\"$cluster\"} == 1)"
    }
   ]
  },
  {
   "title": "Standby Nodes Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(vault_core_active{job=\"$job\", cluster=\"$cluster\"} == 0)"
    }
   ]
  },
  {
   "title": "Active Node History",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vault_core_active{job=\"$job\", cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Lease & Expiry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Active Leases Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(vault_expire_num_leases{job=\"$job\", cluster=\"$cluster\"})",
     "legendFormat": "Total Leases"
    }
   ]
  },
  {
   "title": "Lease Revoke/Renew Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "ops", "label": "Operations per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_expire_revoke_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Revoke Rate"
    },
    {
     "expr": "avg(irate(vault_expire_renew_count{job=\"$job\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Renew Rate"
    }
   ]
  },
  { "title": "Barrier & BoltDB Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Barrier Operations Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(vault_barrier_put_sum{job=\"$job\", cluster=\"$cluster\"}[5m]) / rate(vault_barrier_put_count{job=\"$job\", cluster=\"$cluster\"}[5m]) * 1000)",
     "legendFormat": "Put"
    },
    {
     "expr": "avg(rate(vault_barrier_get_sum{job=\"$job\", cluster=\"$cluster\"}[5m]) / rate(vault_barrier_get_count{job=\"$job\", cluster=\"$cluster\"}[5m]) * 1000)",
     "legendFormat": "Get"
    },
    {
     "expr": "avg(rate(vault_barrier_delete_sum{job=\"$job\", cluster=\"$cluster\"}[5m]) / rate(vault_barrier_delete_count{job=\"$job\", cluster=\"$cluster\"}[5m]) * 1000)",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "BoltDB Store Logs Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(vault_raft_boltdb_storeLogs_sum{job=\"$job\", cluster=\"$cluster\"}[5m]) / rate(vault_raft_boltdb_storeLogs_count{job=\"$job\", cluster=\"$cluster\"}[5m]) * 1000)",
     "legendFormat": "BoltDB Store Logs Time"
    }
   ]
  }
 ]
}