---
- name: Uninstall Vault and related components
  hosts: "vault,vault_dr"
  become: yes
  tasks:
    - name: Stop and disable Vault service
      systemd:
        name: vault
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove Vault package (Debian)
      apt:
        name: vault
        state: absent
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Remove Vault package (RedHat)
      yum:
        name: vault
        state: absent
      ignore_errors: yes
      when: ansible_os_family == "RedHat"

    - name: Remove Vault systemd service files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/systemd/system/vault.service"
        - "/lib/systemd/system/vault.service"
      ignore_errors: yes

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Remove Vault configuration files
      file:
        path: "{{ item }}"
        state: absent
        recurse: yes
      loop:
        - "{{ vault_tls_path }}"
        - "{{ vault_raft_path }}"
        - "/etc/vault.d"
        - "/usr/local/bin/vault"
        - "/var/log/vault.log"
      ignore_errors: yes

    - name: Remove Vault repo files (Debian)
      file:
        path: "{{ item }}"
        state: absent
        recurse: yes
      loop:
        - "/usr/share/keyrings/hashicorp-archive-keyring.gpg"
        - "/etc/apt/sources.list.d/hashicorp.list"
      when: ansible_os_family == "Debian"
      ignore_errors: yes

    - name: Remove HashiCorp repo file (RedHat)
      file:
        path: "/etc/yum.repos.d/hashicorp.repo"
        state: absent
      when: ansible_os_family == "RedHat"
      ignore_errors: yes

    - name: Remove Vault system user
      user:
        name: vault
        state: absent
      ignore_errors: yes

    - name: Stop and disable Keepalived
      systemd:
        name: keepalived
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove Keepalived package (Debian)
      apt:
        name: keepalived
        state: absent
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Remove Keepalived package (RedHat)
      yum:
        name: keepalived
        state: absent
      ignore_errors: yes
      when: ansible_os_family == "RedHat"

    - name: Remove Keepalived configuration files
      file:
        path: "/etc/keepalived/"
        state: absent
        recurse: yes
      ignore_errors: yes

    - name: Remove iptables rules
      file:
        path: "/etc/iptables/rules.v4"
        state: absent
      when:
        - ansible_os_family == "Debian"
        - iptables_install | default(false) | bool
      ignore_errors: yes

    - name: Flush iptables rules
      shell: iptables -F
      when:
        - ansible_os_family == "Debian"
        - iptables_install | default(false) | bool
      ignore_errors: yes

    - name: Remove iptables packages (Debian)
      apt:
        name:
          - iptables
          - iptables-persistent
        state: absent
      ignore_errors: yes
      when:
        - ansible_os_family == "Debian"
        - iptables_install | default(false) | bool

    - name: Stop and disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no
      when:
        - ansible_os_family == "RedHat"
        - firewalld_install | default(false) | bool
      ignore_errors: yes

    - name: Remove firewalld package
      yum:
        name: firewalld
        state: absent
      when:
        - ansible_os_family == "RedHat"
        - firewalld_install | default(false) | bool
      ignore_errors: yes

    - name: Remove auditlog files (Recursive Delete)
      file:
        path: "{{ vault_audit_path }}"
        state: absent
        recurse: yes
      ignore_errors: yes

    - name: Remove backup files (Recursive Delete)
      file:
        path: "{{ backup_path }}"
        state: absent
        recurse: yes
      ignore_errors: yes


    - name: Reboot after uninstall
      reboot:
        msg: "Rebooting after Vault & components removal"
        timeout: 30
      when: reboot_after_uninstall | default(false) | bool
      ignore_errors: yes
