---
- name: "Schedule Vault backup in crontab (only on fist node)"
  cron:
    name: "Vault Backup"
    job: "python3 /usr/local/bin/vault-backup.py"
    user: "root"
    minute: "{{ backup_cron_schedule.split()[0] }}"
    hour: "{{ backup_cron_schedule.split()[1] }}"
    day: "{{ backup_cron_schedule.split()[2] }}"
    month: "{{ backup_cron_schedule.split()[3] }}"
    weekday: "{{ backup_cron_schedule.split()[4] }}"
  when:
    - backup_enabled | default(false) | bool
    - inventory_hostname == groups['vault'][0]
