---
- name: "Deploy backup script"
  template:
    src: "vault-backup.py.j2"
    dest: "/usr/local/bin/vault-backup.py"
    owner: root
    group: root
    mode: '0755'
  when: backup_enabled | default(false) | bool

- name: "Create backup data directory"
  file:
    path: "{{ backup_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: backup_enabled | default(false) | bool