---
- name: "Install chrony (Debian)"
  apt:
    name: chrony
    state: present
    update_cache: yes
  when: 
    - ansible_os_family == "Debian"
    - ntp_servers_enabled | default(false) | bool



- name: "Install chrony (RedHat)"
  yum:
    name: chrony
    state: present
  when: 
    - ansible_os_family == "RedHat"
    - ntp_servers_enabled | default(false) | bool


- name: "Deploy chrony.conf"
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify:
    - restart chrony
  when: 
    - ntp_servers_enabled | default(false) | bool

- name: "Enable & Start chrony (Debian)"
  systemd:
    name: chrony
    enabled: yes
    state: started
  when: 
   - ansible_os_family == "Debian"
   - ntp_servers_enabled | default(false) | bool

- name: "Enable & Start chrony (RedHat)"
  systemd:
    name: chronyd
    enabled: yes
    state: started
  when: 
    - ansible_os_family == "RedHat"
    - ntp_servers_enabled | default(false) | bool
