---
- name: "Update apt cache"
  apt:
    update_cache: yes

- name: "Install base packages"
  apt:
    name:
      - software-properties-common
      - gnupg2
      - gnupg
      - wget
      - python3-pip
    state: present
    update_cache: yes

- name: "Configure /etc/hosts entries"
  lineinfile:
    path: /etc/hosts
    create: yes
    line: "{{ item.ip }}\t{{ item.fqdn }}\t{{ item.short }}"
  loop: "{{ hosts_entries | default([]) }}"
  when: hosts_entries is defined


- name: Disable swap immediately
  command: swapoff -a
  ignore_errors: yes

- name: Disable swap permanently in fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)'
    replace: '# \1'
  notify: reload systemctl daemon
