---
- name: "Ensure Vault audit log directory exists"
  file:
    path: "{{ vault_audit_path }}"
    state: directory
    owner: vault
    group: vault
    mode: '0755'

- name: "Ensure Vault audit log file exists"
  file:
    path: "{{ vault_audit_path }}/vault_audit.log"
    state: touch
    owner: vault
    group: vault
    mode: '0640'

- name: "Retrieve Vault root token"
  set_fact:
    vault_root_token: "{{ lookup('file', vault_key_path) | from_json | json_query('root_token') }}"

- name: "Login to Vault using root token"
  command: vault login {{ vault_root_token }}
  environment:
    VAULT_ADDR: "https://127.0.0.1:8200"
    VAULT_SKIP_VERIFY: "true"
  become: yes
  register: vault_login
  changed_when: false

- name: "Check if Vault audit logging is already enabled"
  command: vault audit list -format=json
  environment:
    VAULT_ADDR: "https://127.0.0.1:8200"
    VAULT_SKIP_VERIFY: "true"
  register: vault_audit_list
  changed_when: false
  become: yes

- name: "Enable Vault Audit Logging if not already enabled"
  command: vault audit enable file file_path={{ vault_audit_path }}/vault_audit.log
  environment:
    VAULT_ADDR: "https://127.0.0.1:8200"
    VAULT_SKIP_VERIFY: "true"
  become: yes
  when:
    - inventory_hostname == groups['vault'][0]
    - "'file/' not in (vault_audit_list.stdout | from_json)"

- name: "Ensure logrotate configuration exists for Vault audit logs"
  copy:
    dest: "{{ auditlog_logrotate_path }}"
    content: |
      {{ vault_audit_path }}/vault_audit.log {
          daily
          rotate {{ auditlog_retention_days }}
          compress
          delaycompress
          notifempty
          create 0640 vault vault
          postrotate
          /usr/bin/killall -HUP vault
          endscript
      }
    owner: root
    group: root
    mode: '0644'

- name: "Test logrotate configuration"
  command: sudo logrotate -v {{ auditlog_logrotate_path }}
  become: yes
